// Class automatically generated by Dev-C++ New Class wizard

#ifndef CHARACTER_H
#define CHARACTER_H
#include <cstdlib>
#include <iostream>

using namespace std;
/*
 This is the parent class, also known as "being".
 */
class Character
{
    private:
            string name;
            int health;
            int damage;
            int defence;
            
             
	public:
		// class constructor
		Character();
		// class destructor
		~Character();
		
		//FUNCTION PROTOTYPES
		//GET AND SET FUNCTIONS
		string get_name();
		void set_name(string);
		
		int get_health();
		void set_health(int);
		
		int get_damage();
		void set_damage(int);
		
		int get_defence();
		void set_defence(int);
	

		
};

#endif // CHARACTER_H
