// Class automatically generated by Dev-C++ New Class wizard

#include "character.h" // class's header file


// class constructor
Character::Character()
{
	// insert your code here
}

// class destructor
Character::~Character()
{
	// insert your code here
}



string Character::get_name()
{ return name;
}

//-----------------------------------------------------------------------------------------------

void Character::set_name(string _name)
{  name = _name;
}

//-----------------------------------------------------------------------------------------------

int Character::get_health()
{ return health;
}

//-----------------------------------------------------------------------------------------------

void Character::set_health(int _health)
{  health = _health;
}

//-----------------------------------------------------------------------------------------------
		
int Character::get_damage()
{ return damage;
}

//-----------------------------------------------------------------------------------------------

void Character::set_damage(int _damage)
{ damage = _damage;
}

//-----------------------------------------------------------------------------------------------

		
int Character::get_defence()
{ return defence;
}

//-----------------------------------------------------------------------------------------------

void Character::set_defence( int _defence)
{ defence = _defence;
}

//-----------------------------------------------------------------------------------------------

