// Class automatically generated by Dev-C++ New Class wizard

#ifndef ITEMS_H
#define ITEMS_H
#include <cstdlib>
#include <iostream>

using namespace std;

// No description
class Items
{   private:
            string name; //Each item has a title
            int effect; //each num is different effect, each type of item has a different effect
            			// 1 is for healthpot, each healthpot contains 1000 health;
			int row; //Each item will have a fixed position.
			int column;
	public:
		// class constructor
		Items();
		// class destructor
		~Items();
		
		//GET AND SET METHODS
		
		void set_name(string);
		string get_name();
		
		void set_effect(int);
		int get_effect();
		
		void set_row(int);
		int get_row();
		
		void set_column(int);
		int get_column();
};

#endif // ITEMS_H
