// Class automatically generated by Dev-C++ New Class wizard

#include "items.h" // class's header file

// class constructor
Items::Items()
{
	// insert your code here
}

// class destructor
Items::~Items()
{
	// insert your code here
}


void Items::set_name(string _name)
{
	name = _name;
}

string Items::get_name()
{
	return name;
}
		
void Items::set_effect(int _effect)
{	effect = _effect;
}

int Items::get_effect()
{ return effect;
}
		
void Items::set_row(int _row)
{ row = _row;
}

int Items::get_row()
{ return row;
}
		
void Items::set_column(int _column)
{ column = _column;
}

int Items::get_column()
{ return column;
}
