// Class automatically generated by Dev-C++ New Class wizard

#include "link.h" // class's header file

// class constructor
Link::Link()
{
	// insert your code here
}

// class destructor
Link::~Link()
{
	// insert your code here
}
