// Class automatically generated by Dev-C++ New Class wizard

#ifndef LINK_H
#define LINK_H

// No description
class Link
{
	public:
 Link * prev;
 char value;
		// class constructor
		Link();
		// class destructor
		~Link();
};

#endif // LINK_H

