// Class automatically generated by Dev-C++ New Class wizard

#ifndef MAZE_H
#define MAZE_H

// No description
class Maze
{
	private: 
            
	public:
		// class constructor
		Maze();
		// class destructor
		~Maze();
		
		//GLOBAL VARIABLES
		static char mazeboard[12][12]; //Manual Maze
		static char mazeboard2[12][12]; //Auto Solver Maze (No monsters and items)
		static bool breadcrumb[12][12]; //Breadcrmb to track where Hero has gone.
		
		//FUNCTION PROTOTYPES
		void display_maze(); //Displays maze
	    void display_maze2();
	    bool isWall(int, int); //Check if it is a wall
	    bool isWall2(int, int); // 2 is for auto solver, 2 for the other maze
	    bool isKey (int, int); 
	    bool isKey2 (int, int);
	    bool isDoor(int, int); //Check Door
	    bool isDoor2(int, int);
	    bool isFinishLine (int, int); //Check Escape
	    bool isMonster(int, int); //Check for Monsters
	    bool isHealth(int, int);
	    bool isWeapon(int, int);
	   
};

#endif // MAZE_H
