// Class automatically generated by Dev-C++ New Class wizard

#include "monster.h" // class's header file

// class constructor
Monster::Monster()
{
	// insert your code here
}

// class destructor
Monster::~Monster()
{
	// insert your code here
}
