// Class automatically generated by Dev-C++ New Class wizard

#ifndef WEAPON_H
#define WEAPON_H
#include "items.h"
//Child of Items
// No description
class Weapon : public Items
{   private:
	
	int damage;
            
	public:
		// class constructor
		Weapon();
		// class destructor
		~Weapon();
		
	void set_damage(int);
	int get_damage();
};

#endif // WEAPON_H
