// Class automatically generated by Dev-C++ New Class wizard

#include "weapon.h" // class's header file

// class constructor
Weapon::Weapon()
{
	// insert your code here
}

// class destructor
Weapon::~Weapon()
{
	// insert your code here
}


void Weapon::set_damage(int _damage)
{ damage = _damage;
}

int Weapon::get_damage()
{ return damage;
}
